default:
  just --choose

build_container:
  # Build the container.
  docker build --tag almalinux8p10_build .

enter_interactive:
  # Enter the docker container in interactive mode.
  docker run --interactive --tty --rm \
  --mount type=bind,source=$(pwd),target=/home/neo \
  almalinux8p10_build
