[project]
name = "pi"
version = "1.1.0"
description = "A maximalist (and bloated) batteries included python 3.14 appimage for Electrical engineering workflows. WASM friendly!"
readme = "README.md"
requires-python = "==3.14.6"
license = "CC0-1.0"
authors = [
  { name = "Siddhant Laddha", email = "25705822+siddhantladdha@users.noreply.github.com" }
]
maintainers = [
  { name = "Siddhant Laddha", email = "25705822+siddhantladdha@users.noreply.github.com" }
]
classifiers = [
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "Private :: Do Not Upload",
  "Topic :: Scientific/Engineering",
]
dependencies = [
  # Use the following for any utility functions and data structures
  # instead of writing your own.
  "boltons>=25.0.0",
  # for any cli applications/interfaces.
  "cyclopts>=4.11.0; sys_platform != 'emscripten'",
  # Generate code from schemas for better interoperability between tools.
  "datamodel-code-generator",
  # Tabular data exports
  "great-tables>=0.22.0",
  "hy",  # evaluating versus sexpdata for lisp interface.
  # use the following for testing and test coverage.
  "hypothesis>=6.152.3",
  # marimo goodies.
  "marimo[lsp]",
  "marimo[mcp]",
  "marimo[recommended]",
  # Only use this if polars and xarray cannot do a task.
  "numpy>=2.4.4",
  "pandas>=3.0.2",
  # Use the following for parsing in case user explicitly asks.
  "parsimonious>=0.11.0",  # maybe pyparsing is more ergonomic. evaluate.
  # use plotly instead of matplotlib.
  "plotly>=6.7.0",
  # Use this if you really need to use multiple subprocess/shell functions.
  "plumbum>=1.10.0; sys_platform == 'linux'",
  # use polars instead of pandas.
  "polars>=1.40.1",
  "polars-mcp",
  # in rare cases where you need to actually read psf data.
  "psf_utils>=1.10",
  # for interactive use by user.
  "ptpython>=3.0.32; sys_platform != 'emscripten'",
  # Use pydantic for data validation.
  "pydantic>=2.13.3",
  "pydantic-settings",
  # Use the following for parsing by default.
  "pyparsing>=3.3.2",
  # use the following for testing.
  "pytest>=9.0.3",
  # If you don't use units and SI prefixes, fuck you.
  "quantiphy>=2.21",
  # use this for logging, pretty printing and traceback.
  "rich>=15.0.0",
  # formatter and linter for python code.
  "ruff",
  # engineering specific libraries.
  "scipy>=1.17.1",
  # in rare cases where you need to interact with SKILL/SKILL++/Scheme.
  "sexpdata",
  # symbolic math is love!
  "sympy>=1.14.0",
  # for functional programming.
  "toolz>=1.1.0",
  # type checker.
  "ty",
  "wigglystuff",  # trying this marimo widget out for fun.
  # use xarray instead of numpy.
  "xarray>=2026.4.0",
  ## Archives/TBD
  # "polarise>=1.1.0",
  # "flowview",
]

[project.urls]
Homepage = "https://sid555.com/pwa/marimo/pi/"
Repository = "https://github.com/siddhantladdha/misc/tree/main/python_appimage/"
