# Where should we write the GIF?
Output demo.gif
# Require any programs we need to run the demo.
# Require bat
## Cosmetics
# Set up a 1200x600 terminal with 46px font.
Set FontSize 46
Set Width 1200
Set Height 600
Set Theme "Dracula"
Set Padding 20
Set TypingSpeed 50ms
Set Shell fish
# Actual command
Type "echo 'Welcome to VHS!'"
Sleep 200ms
Enter
# At any point take a screenshot
# Screenshot examples/screenshot.png

# Admire the output for a bit.
Sleep 3s
