name: Python/xonsh script runner.

env:
    # github username of package repository
    PKG_USERNAME: "xonsh"
    PKG_NAME: "xonsh"
    PKG_VERSION: "0.22.8"
    PKG_SHA256: 13673b916ea534574f5666b6712a57cb8373b010857da49bd12312c760537226
    PKG_HOST_URL: "https://github.com"
    PKG_HOST_URL_STUB: "releases/download"
    PKG_PLATFORM: "x86_64"
    PKG_EXT: ".AppImage"
    PKG_TARGET_DIR: "/usr/local/bin"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      script_name:
        description: "Name of script"
        required: false
        default: "hello.xsh"
        type: string

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "python-runner"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Xonsh
        run: |
          # fail on error and print commands
          set -ex
          wget --output-document=${{ env.PKG_TARGET_DIR }}/${{ env.PKG_NAME }} ${{ env.PKG_HOST_URL }}/${{ env.PKG_USERNAME }}/${{ env.PKG_NAME }}/${{ env.PKG_HOST_URL_STUB }}/${{ env.PKG_VERSION }}/${{ env.PKG_NAME }}-${{ env.PKG_PLATFORM }}${{ env.PKG_EXT }}\
          && echo "${{ env.PKG_SHA256 }}  ${{ env.PKG_TARGET_DIR }}/${{ env.PKG_NAME }}" | sha256sum --check\
          && chmod u+x ${{ env.PKG_TARGET_DIR }}/${{ env.PKG_NAME }}
  
      - name: Checkout scripts only
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/workflows/scripts/
          sparse-checkout-cone-mode: false

      - name: Run Scripts
        run: |
          xonsh .github/workflows/scripts/${{ inputs.script_name }}